name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 pycodestyle
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
    - name: Lint with flake8
      run: |
        flake8 . --max-line-length=127 --max-complexity=10 --show-source
    - name: Lint with pycodestyle
      run: |
        pycodestyle .
