name: Build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint `find -regextype egrep -regex '(.*.py)$'`
    - name: YAML Lint
      # You may pin to the exact commit or the version.
      # uses: ibiqlik/action-yamllint@b2aeacc1b7eeb8c23e84bba320d04fb5d6a323ee
      uses: ibiqlik/action-yamllint@v3.0.0
      with:
        # File(s) or Directory, separate by space if multiple files or folder are specified
        file_or_dir: config.yml
  
